### ISSUE TITLE
NdP: aggiungere revisione con pull request

### ISSUE THREAD

**Issue by marcovolpato00** [Bug-s-Bunny-Team/docs#28]
Esempio con verbale:
- redattore redige verbale e apre pull request su branch dev
- assegna pull request a verificatore e approvatore
- verificatore verifica e propone modifiche o modifica direttamente
- approvatore applica approvazione finale ed chiede pull request

**Comment by marcovolpato00** [comment]
I nostri repo fin'ora usano come branch principale `master` e non `main`

**Comment by BlackWolf00** [comment]
Si lo cambio, grazie della nota, colpa dell'abitudine
