### ISSUE TITLE
Norme di Progetto

### ISSUE THREAD

**Issue by marcovolpato00** [Bug-s-Bunny-Team/docs#3]
Trasposizione in Latex delle Norme di Progetto
- [x] Aggiungere a norme di progetto il sistema delle issues
- [x] Processo di validazione: aggiungere aspettative
- [x] Aggiungere vari servizi Amazon nel paragrafo 2.2.5
- [x] Completare Registro delle modifiche

**Comment by mhetacc** [comment]
Aggiungere a norme di progetto il sistema delle issues
