### ISSUE TITLE
NdP Aggiornamento

### ISSUE THREAD

**Issue by mhetacc** [Bug-s-Bunny-Team/docs#46]
- [x] riportare metriche qualità e scrivere formule
- [x] controllare coerenza rispetto a PdP
- [x] riportare le metriche sotto le singole sezioni
- [x] riportare iso 12207 
- [x] riportare iso 25000
- [x] #58
- [x] verificare sia presente automiglioramento, in caso riportarlo
- [x] riportare nuovi riferimenti informativi (nuovi iso and such)
- [x] registro modifiche, numero sezione versione 0.1.4
- [x] norme tipografiche scrittura liste

**Comment by mhetacc** [comment]
PdQ sezione 3 e credo anche 4 partono con "[...] come riportato nel NdQ".
Date un occhio.

**Comment by BlackWolf00** [comment]
Ho aggiunto dei task
