### ISSUE TITLE
Update Glossario

### ISSUE THREAD

**Issue by angelaarena** [Bug-s-Bunny-Team/docs#59]
- [x] use case, casi d'uso ripetizione
- [x] "neptune" senza definizione
- [x] Tik Tok
- [x] Instagram
- [x] ISO 12207, 15504, 25000
- [x] Modello a V
- [x] Latex
- [x] V&V
- [x] Google Docs
- [x] Design Pattern
- [x] Google Drive
- [x] AdR
- [x] Visual Studio Code (VSC)
- [x] Scraper \ Crawler
- [x] Sprint
- [x] Baseline
- [x] Backend
- [x] Frontend
- [x] Serverless
- [x] Unit Tests

**Comment by BlackWolf00** [comment]
Per Use Case/Casi d'uso: sotto una delle due voci si può scrivere: fare riferimento a " " e si aggiunge l'alternativa

**Comment by marcovolpato00** [comment]
- [ ] ban
- [ ] Comprehend
- [ ] Rekognition
