### ISSUE TITLE
Verbali - aggiungere lista issue aperte

### ISSUE THREAD

**Issue by marcovolpato00** [Bug-s-Bunny-Team/docs#87]
> 3) le decisioni prese devono entrare esplicitamente e quindi anche in modo tracciabile nel verbale stesso, nel vostro sistema di issue tracking (o sistema di assegnazione di azioni). 

Va fatta una lista delle issue aperte, scaturite dalla riunione. Riportare numero issue e magari titolo.

**Comment by BlackWolf00** [comment]
Era per il verbale di ieri o per tutti ?

**Comment by marcovolpato00** [comment]
Solo quello di ieri

**Comment by marcovolpato00** [comment]
Lascio issue aperta come reminder per aggiungere anche nel template.

**Comment by BlackWolf00** [comment]
Ok va bene
